const seatData  = {
  GK302A: [
    { occupied: true, user: { name: "Student 1", anonymous: false } },
    { occupied: false, user: null },
    { occupied: true, user: { name: "Anonymous", anonymous: true } },
    { occupied: false, user: null },
    { occupied: true, user: { name: "Student 2", anonymous: false } },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
  ],
  GK302B: [
    { occupied: true, user: { name: "Student 3", anonymous: false } },
    { occupied: true, user: { name: "Anonymous", anonymous: true } },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: true, user: { name: "Student 4", anonymous: false } },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },

  ],
  GK306A: [
    { occupied: false, user: null },
    { occupied: true, user: { name: "Student 5", anonymous: false } },
    { occupied: true, user: { name: "Anonymous", anonymous: true } },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
  ],
  GK404A: [
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: true, user: { name: "Student 6", anonymous: false } },
    { occupied: true, user: { name: "Anonymous", anonymous: true } },
    { occupied: true, user: { name: "Student 7", anonymous: false } },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
  ],
  GK404B: [
    { occupied: true, user: { name: "Anonymous", anonymous: true } },
    { occupied: false, user: null },
    { occupied: true, user: { name: "Student 8", anonymous: false } },
    { occupied: false, user: null },
    { occupied: true, user: { name: "Student 9", anonymous: false } },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },
    { occupied: false, user: null },

  ]
};

export default seatData;